WIP: Fix issue #16
craftup/node-mongo-tenant pull request #36
Opened 2018-03-13 07:34 UTC by baranga

Fix issue #16

2018-03-14 16:47 UTC, alrik requested changes

2018-03-14 16:47 UTC, alrik commented on index.js
> +   * plugin installed installed in these models is compatible to the plugin of
_installed installed_

2018-03-14 16:47 UTC, alrik commented on index.js
> +      getMongoTenantPluginInstance: function () {
what about making it a property?

```js
get mongoTenant() {
  return me;
}
```

2018-03-14 16:47 UTC, alrik commented on index.js
> +        plugin => (plugin.fn === mongoTenantPlugin)
i think the other plugin does not need to be the same module :thinking:
in scenarios where you split your models up into separate packages we might have different mongo-tenant references.

2018-03-14 16:47 UTC, alrik commented on index.js
> +  createBoundDb(unboundDb, tenantId) {
I would go with `createTenantAwareDb` to have consistent naming.

2018-03-14 16:47 UTC, alrik commented on index.js
> +          modelCache[tenantId] = me.createTenantAwareModel(Model, tenantId, boundDb);
it feels like the db with tenant context should be created within `createTenantAwareModel`

2018-03-14 16:47 UTC, alrik commented on index.js
> +      plugin instanceof MongoTenant &&
I think `instanceOf``is not safe to use in multi-package setups.

2018-03-14 17:00 UTC, alrik commented
Awesome @baranga :1st_place_medal: 

It might be part of another issue, but do you know what happens,
when you save a cross tenant ref?

```js
const subSchema = new Schema({});
const parentSchema = new Schema({
  sub: [{ type: Schema.Types.ObjectId, ref: 'Sub' }]
});
subSchema.pluging(mongoTenant);
parentSchema.plugin(mongoTenant);
const Sub = mongoose.model('Sub', subSchema);
const Parent = mongoose.model('Person', parentSchema);

const sub = await Sub.byTenant('tenant-1').create({});
const parent = await Parent.byTenant('tenant-2').create({ sub: sub._id });
```

2018-03-18 12:12 UTC, baranga commented
@alrik this will save the references in the database but don't populate them back if fetched in a tenant context. See https://github.com/craftup/node-mongo-tenant/blob/a04f92f7b0def5abf4cbfe616df9dd42e5e4a5af/test/middleware.js#L124

2018-03-18 18:23 UTC, baranga commented on index.js
> +      getMongoTenantPluginInstance: function () {
Don't know if that works for schema statics.

2018-03-19 18:51 UTC, baranga commented on index.js
> +      getMongoTenantPluginInstance: function () {
It works :)

2018-03-19 18:52 UTC, baranga commented
@alrik Incorporated all your changes. Could you review again please?

2018-12-15 01:54 UTC, sashahilton00 commented
Is there any reason that this never made it into master?

2019-03-18 16:47 UTC, alrik commented
@sashahilton00 sorry for this very late response :crying_cat_face: 
There was not enough pressure behind this issue :)
This issue comes with some conceptual complexity and i did not took the time yet to test every potential side effect...
Do you need this feature implemented?

2019-03-20 11:09 UTC, sashahilton00 commented
Not a problem @alrik, we have used a couple of hacky workarounds, but it would be good to get this merged at somepoint as we can tidy up our codebase a little once it is.

2019-03-20 13:06 UTC, baranga commented
@alrik I merged develop and fixed an infinite loop bug unveiled by the new tests cases from that merge.

2019-03-20 13:49 UTC, alrik commented
Nice. I'll have a final look on it tomorrow.

2019-03-20 14:16 UTC, alrik commented
@baranga I don't like to introduce a BC break :thinking: 
couldn't we define the schema property like this?
```js
constructor(schema, options) {
    this._modelCache = {};
    this.options = options || {};

    Object.defineProperty(this, 'schema', {
      get() {
        return schema;
      },
    });
}
```

2019-03-20 19:01 UTC, baranga commented
@alrik the issue I tried to solve with the latest commit was a infinite loop happening on dump deep merge of two schemas. I wonder if two plugin instance should be merged at all :thinking:

So maybe it would be best to define all properties in the get style. But that may cause BC issues again. Sounds like we should either not expose anything in 2.0 or at least document that the plugin internals are subject of changes (which should be the default case any way).

2019-03-21 09:24 UTC, alrik approved these changes

2019-03-21 09:36 UTC, merged