Fix discriminator key descriptor problem closes #34
craftup/node-mongo-tenant pull request #39
Opened 2018-06-15 14:36 UTC by felipe-augusto

Fixes the discriminator key problem, where the property is not writable.

2018-06-18 08:56 UTC, alrik commented
Hey @felipe-augusto,

thanks a lot for fixing this issue.
Could you add a test case?

Cheers :)

2018-06-18 08:58 UTC, alrik requested changes

2018-06-18 08:58 UTC, alrik commented on index.js
> +      let descriptor = Object.getOwnPropertyDescriptor(BaseModel, staticProperty)
Please add a semicolon to the end of line, so that the codebase stays consistent. Thx

2018-06-18 14:59 UTC, felipe-augusto commented
I don't know if the test I wrote is in the right place, can you confirm it @alrik?

2018-06-19 09:38 UTC, alrik approved these changes

2018-06-19 09:53 UTC, alrik commented
Thanks @felipe-augusto,
looks good to me.

Yes, there are some strage timeouts with travis :(
I restarted the pipeline and everything is fine :+1:

2018-06-19 09:54 UTC, merged