Fixes problem of adding tenant to model discriminators
craftup/node-mongo-tenant pull request #40
Opened 2018-07-05 18:40 UTC by felipe-augusto

When creating a discriminator and using together with node-mongo-tenant, we should also apply tenant to all model discriminators, otherwise tenant does not works.

2018-07-05 18:41 UTC, felipe-augusto commented
@alrik After this is merged, can you please release a new version?

2018-07-05 20:26 UTC, alrik requested changes

2018-07-05 20:26 UTC, alrik commented on index.js
> +    if(BaseModel.discriminators) {
Just minor cosmetics: could you be so kind and add a space after `if`.
Thanks :heart:

2018-07-06 07:12 UTC, alrik approved these changes

2018-07-06 07:13 UTC, merged

2018-07-06 16:27 UTC, alrik commented
Refers to #38

2018-07-06 16:28 UTC, alrik commented
@felipe-augusto I finally made it to release version 1.5.0 :tada:

2018-07-08 20:43 UTC, felipe-augusto commented
Thanks @alrik. Great work!