Update integration.js
craftup/node-mongo-tenant pull request #42
Opened 2019-01-19 09:26 UTC by himbaer

Tests added for https://github.com/craftup/node-mongo-tenant/issues/41

2019-01-24 12:06 UTC, alrik requested changes
Thx for your contribution. Looks good to me. :+1: 
Before i merge this, could you remove your debug statements.

2019-01-24 12:06 UTC, alrik commented on test/integration.js
> +              console.log(err);
@himbaer could you remove those two `console.log` - debug statements?

2019-01-24 13:18 UTC, himbaer commented on test/integration.js
> +              console.log(err);
Done via https://github.com/craftup/node-mongo-tenant/pull/42/commits/74d49d59017551e9e49b0fb4c61a916eb94327de

2019-03-18 16:33 UTC, alrik approved these changes

2019-03-18 16:48 UTC, merged